perhaps minimally-viable on mac

diff --git a/src/quig b/src/quig
--- a/src/quig
+++ b/src/quig
@@ -75,7 +75,14 @@ function quig_extract(){
 
 function quig_list()
 {
-    local path_array=($quarto_directory/*/bin/quarto)
+    local path_spec="$quarto_directory/*/bin/quarto"
+    local path_array=($path_spec)
+
+    # test to see if nothing found
+    if [[ "$path_array" == "$path_spec" ]]; then
+        echo >&2 "No Quarto versions found at $quarto_directory"
+        exit 1
+    fi
 
     local version_array=()
     for path in "${path_array[@]}"
@@ -164,6 +171,11 @@ function quig_add()
 
     # create directory
     mkdir -p "$quarto_directory/$version"
+    local exit_status=$?
+    if [ $exit_status -gt 0 ]; then
+        echo >&2 "ERROR: Cannot create directory $quarto_directory/$version."
+        exit 1
+    fi
 
     # determine download URL
     local url=$(quig_tar_url $version)
@@ -189,8 +201,48 @@ function quig_add()
 
 function quig_rm()
 {
+
+    local version="$1"
+
+    # does directory exist?
+    if [[ ! -d "$quarto_directory/$version" ]]; then
+        echo >&2 "ERROR: Quarto version $version not found."
+        exit 1
+    fi
+
     # don't delete default
-    echo "not done yet"
+    local version_default=$(quig_default)
+    if [[ "$version" == "$version_default" ]]; then
+        echo >&2 "ERROR: $version is the default version, won't delete."
+        exit 1
+    fi
+
+    # delete
+    rm -r "$quarto_directory/$version"
+    echo >&2 "Deleted Quarto version $version"
+
+    echo "$version"
+    exit 0
+}
+
+function quig_clean()
+{
+
+    if ! local version_array=($(quig_list)); then
+        echo "No versions found"     
+        exit 1
+    fi
+    
+    local version_default=$(quig_default)
+
+    for version in "${version_array[@]}"
+    do
+        if [[ "$version" != "$version_default" ]]; then
+            local result=$(quig_rm $version)
+        fi
+    done
+
+    exit 0
 }
 
 function quig_help()
@@ -220,6 +272,7 @@ function quig_help()
     echo "\n"
     echo "SUBCOMMANDS:\n"
     echo "\t  add\n"
+    echo "\t  clean\n"
     echo "\t  default\n"
     echo "\t  help\n"
     echo "\t  list\n"
@@ -244,7 +297,10 @@ function quig_help()
     echo "\t  sudo quig default 1.3.290\n"
     echo "\n"
     echo "\t  # Add pre_release version, set as default, remove all other versions\n"
-    echo "\t  quig upgrade pre_release\n"
+    echo "\t  sudo quig upgrade pre_release\n"
+    echo "\n"
+    echo "\t  # Remove all versions except default\n"
+    echo "\t  sudo quig clean\n"    
 }
 
 if [[ "$1" == "resolve" ]]; then
@@ -262,19 +318,42 @@ fi
 
 if [[ "$1" == "add" ]]; then
 
+    # elevate permissions, if needed
+    if [ "$EUID" != 0 ]; then
+        echo "Requires sudo privilges."
+        sudo "$0" "$@"
+        exit $?
+    fi
+
     version=$(quig_add $2)
     exit_status=$?    
     if [ $exit_status -gt 0 ]; then
         echo >&2 "Quarto version $2 not installed."
         exit 1
     fi
-    
     echo "Added Quarto $version to \`$quarto_directory\`"    
+
+    # if no default, set default
+    version_default=$(quig_default)
+    exit_status=$?    
+    if [ $exit_status -gt 0 ]; then
+        # need to set default
+        version_default=$(quig_default $version)
+        echo "Set Quarto $version as default."    
+    fi    
+
     exit 0    
 fi
 
 if [[ "$1" == "default" ]]; then
-    
+
+    # elevate permissions, if needed
+    if [ "$EUID" != 0 ]; then
+        echo "Requires sudo privilges."
+        sudo "$0" "$@"
+        exit $?
+    fi
+
     version=$(quig_default $2)
     exit_status=$?    
     if [ $exit_status -gt 0 ]; then
@@ -290,7 +369,6 @@ if [[ "$1" == "list" ]]; then
 
     # use outer set of parens to parse array
     if ! version_array=($(quig_list)); then
-        echo "No versions found"     
         exit 1
     fi
     
@@ -307,7 +385,84 @@ if [[ "$1" == "list" ]]; then
     exit 0   
 fi
 
+if [[ "$1" == "rm" ]]; then
+
+    # elevate permissions, if needed
+    if [ "$EUID" != 0 ]; then
+        echo "Requires sudo privilges."
+        sudo "$0" "$@"
+        exit $?
+    fi
+
+    version=$(quig_rm $2)
+    exit_status=$?    
+    if [ $exit_status -gt 0 ]; then
+        exit 1
+    fi
+
+    exit 0
+fi
+
+if [[ "$1" == "clean" ]]; then
+
+    # elevate permissions, if needed
+    if [ "$EUID" != 0 ]; then
+        echo "Requires sudo privilges."
+        sudo "$0" "$@"
+        exit $?
+    fi
+
+    version=$(quig_clean)
+    exit_status=$?    
+    if [ $exit_status -gt 0 ]; then
+        exit 1
+    fi
+
+    exit 0
+fi
+
+if [[ "$1" == "upgrade" ]]; then
+
+    # elevate permissions, if needed
+    if [ "$EUID" != 0 ]; then
+        echo "Requires sudo privilges."
+        sudo "$0" "$@"
+        exit $?
+    fi
+    
+    # add
+    version=$(quig_add $2)
+    exit_status=$?    
+    if [ $exit_status -gt 0 ]; then
+        echo >&2 "Quarto version $2 not installed."
+        exit 1
+    fi
+
+    # set default
+    version=$(quig_default $version)
+    exit_status=$?    
+    if [ $exit_status -gt 0 ]; then
+        echo >&2 "ERROR: Cannot set default Quarto version."
+        exit 1
+    fi
+
+    echo "Default quarto version is $version"    
+
+    # clean
+    version=$(quig_clean)
+    exit_status=$?    
+    if [ $exit_status -gt 0 ]; then
+        exit 1
+    fi
+
+    exit 0
+fi
+
 if [[ "$1" == "help" || -z $1 ]]; then
     echo -e $(quig_help)
     exit 0
 fi
+
+# no options recignized
+echo >&2 "ERROR: option \`${1}\` not recognized; use \`quig help\` to see options."
+exit 1
